jobs:
  macos:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: brew install nsis makeself
    - continue-on-error: true
      run: ant pkgbuild
    - continue-on-error: true
      run: echo "Setting CA trust settings to 'allow' (https://github.com/actions/runner-images/issues/4519)"
    - continue-on-error: true
      run: security authorizationdb read com.apple.trust-settings.admin > /tmp/trust-settings-backup.xml
    - continue-on-error: true
      run: sudo security authorizationdb write com.apple.trust-settings.admin allow
    - continue-on-error: true
      run: sudo installer -pkg out/qz-tray-*.pkg -target /
    - continue-on-error: true
      run: echo "Restoring CA trust settings back to default"
    - continue-on-error: true
      run: sudo security authorizationdb write com.apple.trust-settings.admin < /tmp/trust-settings-backup.xml
    - continue-on-error: true
      run: '''/Applications/QZ Tray.app/Contents/MacOS/QZ Tray'' --version'
    - continue-on-error: true
      run: ant makeself
    - continue-on-error: true
      run: ant nsis
    strategy:
      matrix:
        java:
        - 11
        - 17
  ubuntu:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: sudo apt-get install nsis makeself
    - continue-on-error: true
      run: ant makeself
    - continue-on-error: true
      run: sudo out/qz-tray-*.run
    - continue-on-error: true
      run: /opt/qz-tray/qz-tray --version
    - continue-on-error: true
      run: ant nsis
    strategy:
      matrix:
        java:
        - 11
        - 17
  windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: choco install nsis
    - continue-on-error: true
      run: ant nsis
    - continue-on-error: true
      run: Start-Process -Wait ./out/qz-tray-*.exe -ArgumentList "/S"
    - continue-on-error: true
      run: '&''C:/Program Files/QZ Tray/qz-tray.exe'' --wait --version|Out-Null'
    strategy:
      matrix:
        java:
        - 11
        - 17
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yaml
